services:
  server:
    build: ./client
    ports:
      - "5050:5000"
    command: npm run dev
    volumes:
      - ./server/src:/app/src

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - ./client/src:/app/src

  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
